" Begin .vimrc

"colorscheme delek
"colorscheme desert256
"colorscheme desert
colorscheme distinguished

set nocompatible
set autowrite

set sessionoptions=buffers,curdir,folds,resize,tabpages
set encoding=utf-8
set laststatus=2
set number
set relativenumber
set showcmd
set foldmethod=syntax

set incsearch
set nohlsearch
set ignorecase
set smartcase
set keymap=russian-jcukenwin
set iminsert=0
set imsearch=0

set nobackup
set nowritebackup
set grepprg=grep\ -nr

set autoindent
set expandtab
set tabstop=2
set shiftwidth=2

set path=.,,**

""" VCSCommand plugin options
let VCSCommandGitDiffOpt='--no-prefix'
let g:netrw_browsex_viewer="xdg-open"
let g:gs_indent_log=0
"nmap <leader>gi <Plug>VCSAnnotate :!git show <C-R><C-W><CR> :q<CR>

let g:gist_clip_command='xclip'

set cursorline
autocmd WinEnter * set cursorline
autocmd WinLeave * set nocursorline
highlight lCursor guifg=NONE guibg=Cyan
"au WinLeave * set nocursorline nocursorcolumn
"au WinEnter * set cursorline cursorcolumn
"hi CursorLine cterm=NONE ctermbg=242
"hi CursorLine cterm=reverse

set spelllang=en,ru
autocmd FileType markdown,tex,text set spell
"map <silent> <leader>sc :set spell<CR>
"map <silent> <leader>ns :set nospell<CR>

"vmap <F2> y:call system("xlicp -i -selection clipboard", getreg("\""))<CR>:call system("xclip -i", getreg("\""))<CR>
"nmap <F3> :call setreg("\"",system("xclip -o -selection clipboard"))<CR>p

"map <F4> [I:let nr = input("Which one: ")<Bar>exe "normal " . nr ."[\t"<CR>
map <F4> :vsplit<CR><C-W>l:grep <C-R><C-W> *<CR>:copen<CR>
"map <F5> :make<CR>
"map <F6> :make<CR>:cwindow<cr><cr>
"imap [ []<LEFT>
"imap ( ()<LEFT>
"imap { {}<LEFT>
"imap <C-L> <C-O>a
"map <F9> :exec ":!./$(find -type f -executable | head -1)".<CR><CR>

filetype plugin indent on
runtime! ftplugin/man.vim

autocmd BufWritePre * :%s/\s\+$//e
autocmd BufWritePost $MYVIMRC source $MYVIMRC
autocmd BufWritePost *.c,*.cc,*.cpp,*.h silent make -k | unsilent redraw! | cwindow

" Fix weird colors in vimdiff
"highlight DiffAdd cterm=none ctermfg=bg ctermbg=Green gui=none guifg=bg guibg=Green
"highlight DiffDelete cterm=none ctermfg=bg ctermbg=Red gui=none guifg=bg guibg=Red
"highlight DiffChange cterm=none ctermfg=bg ctermbg=Yellow gui=none guifg=bg guibg=Yellow
"highlight DiffText cterm=none ctermfg=bg ctermbg=Magenta gui=none guifg=bg guibg=Magenta

" End .vimrc
