#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap
torrents=torrents/
rtorrent_lock=$torrents/.session/rtorrent.lock

# Set keyboard layout
setxkbmap -model pc105 -layout "us,ru(winkeys)" -option "grp:alt_shift_toggle,grp:led_scroll"
# Merge in defaults and keymaps
[ -f $sysresources ] && /usr/bin/xrdb -merge $sysresources
[ -f $sysmodmap ] && /usr/bin/xmodmap $sysmodmap
[ -f $userresources ] && /usr/bin/xrdb -merge $userresources
[ -f $usermodmap ] && /usr/bin/xmodmap $usermodmap
# Run programs
urxvtd -q -o -f
screen -wipe

screen -list | pgrep irssi || screen -dmS irssi irssi
screen -list | pgrep mcabber || screen -dmS mcabber mcabber

screen -list | pgrep rtorrent || rm -rf $rtorrent_lock && screen -dmS rtorrent rtorrent 

urxvtc -T irssi -e screen -r irssi &
urxvtc -T mcabber -e screen -r mcabber &

xsetroot -cursor_name left_ptr

# exec /usr/bin/xmonad
exec /usr/bin/i3 --force-xinerama -V > ~/.config/i3/i3.log 2>&1
#exec /usr/bin/i3 -V > ~/.config/i3/i3.log 2>&1
