---
- name: Ensure ~/.config exists
  file:
    path: "{{ lookup('env', 'HOME') }}/.config"
    state: directory

- name: Symlink per-tool dirs into ~/.config
  file:
    src: "{{ playbook_dir }}/../../dotfiles/{{ item }}"
    dest: "{{ lookup('env', 'HOME') }}/.config/{{ item }}"
    state: link
    force: "{{ overwrite_existing }}"
  loop:
    - emacs
    - tmux
    - vim

- name: Ensure ~/.config/git exists
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/git"
    state: directory

- name: Symlink individual files into ~/.config/git
  file:
    src: "{{ playbook_dir }}/../../dotfiles/git/{{ item }}"
    dest: "{{ lookup('env', 'HOME') }}/.config/git/{{ item }}"
    state: link
    force: "{{ overwrite_existing }}"
  loop:
    - config
    - ignore

- name: Symlink ~/.toprc
  file:
    src: "{{ playbook_dir }}/../../dotfiles/toprc"
    dest: "{{ lookup('env', 'HOME') }}/.toprc"
    state: link
    force: "{{ overwrite_existing }}"

- name: Symlink ~/bin
  file:
    src: "{{ playbook_dir }}/../../dotfiles/bin"
    dest: "{{ lookup('env', 'HOME') }}/bin"
    state: link
    force: "{{ overwrite_existing }}"
